version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "**/*"
      - "!/task/v2"
    schedule:
      interval: "weekly"
    target-branch: "main"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
