name: '2.0$(rev:.r)'

trigger:
  batch: true
  branches:
    include:
      - main
      - develop
      - feature/*
      - fix/*
  paths:
    exclude:
      - LICENSE.md
      - README.md

pool:
  vmImage: 'ubuntu-latest'

variables:
  publisher: 'foxholenl'
  extensionId: 'Gitleaks'
  extensionName: 'Gitleaks'

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: 
        variables:
          system.debug: true
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'
          - task: SonarCloudPrepare@3
            inputs:
              SonarCloud: 'SonarCloud'
              organization: 'joostvoskuil'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: 'JoostVoskuil_azure-devops-gitleaks'
              cliProjectName: 'JoostVoskuil_azure-devops-gitleaks'
              cliSources: '.'
              extraProperties: |
                sonar.coverage.exclusions=task/v2/test/*.ts,task/v3/test/*.ts
                sonar.cpd.exclusions=task/v2/test/*.ts,task/v3/test/*.ts,**/node_modules/**
          - template: build-and-test.yml
            parameters:
              path: task/v2
              name: Gitleaks V2
          - template: build-and-test.yml
            parameters:
              path: task/v3
              name: Gitleaks V3
          - task: SonarCloudAnalyze@3
            inputs:
              jdkversion: 'JAVA_HOME_17_X64'
          - task: SonarCloudPublish@3
            inputs:
              pollingTimeoutSec: '300'
          - task: TfxInstaller@4
            displayName: 'Use Node CLI for Azure DevOps'
            inputs:
              version: '0.x'
              checkLatest: true
          - task: PackageAzureDevOpsExtension@5
            displayName: 'Package Extension DEV'
            inputs:
              rootFolder: '$(Build.SourcesDirectory)'
              outputPath: '$(Build.ArtifactStagingDirectory)/foxholenl-gitleaks-private.vsix'
              publisherId: $(publisher)
              extensionId: $(extensionId)
              extensionName: $(extensionName)
              extensionTag: '-dev'
              extensionVersion: '$(Build.BuildNumber)'
              extensionVisibility: privatepreview
          - task: PackageAzureDevOpsExtension@5
            displayName: 'Package Extension PROD'
            inputs:
              rootFolder: '$(Build.SourcesDirectory)'
              outputPath: '$(Build.ArtifactStagingDirectory)/foxholenl-gitleaks-public.vsix'
              publisherId: $(publisher)
              extensionId: $(extensionId)
              extensionName: $(extensionName)
              extensionVersion: '$(Build.BuildNumber)'
              extensionVisibility: public
          - task: PublishPipelineArtifact@1
            displayName: 'Publish vsix'
            inputs:
              publishLocation: pipeline
              targetPath: '$(Build.ArtifactStagingDirectory)/*.vsix'
              artifact: 'vsix'
            condition: succeededOrFailed()

  - stage: DeployDEV
    displayName: 'Publish to Marketplace (private)'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    dependsOn: [Build]
    jobs:
      - deployment:
        environment: Test
        strategy: 
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: vsix
                  patterns: "**/*-private.vsix"
                - task: TfxInstaller@4
                  displayName: 'Use Node CLI for Azure DevOps'
                  inputs:
                    version: '0.x'
                    checkLatest: true
                - task: PublishAzureDevOpsExtension@5
                  displayName: 'Publish Extension'
                  inputs:
                    connectTo: 'VsTeam'
                    connectedServiceName: 'Marketplace'
                    fileType: 'vsix'
                    vsixFile: '$(Pipeline.Workspace)/vsix/foxholenl-gitleaks-private.vsix'
                    updateTasksVersion: false
                    shareWith: 'foxholenl'
                    noWaitValidation: true

  - stage: DeployPROD
    displayName: 'Publish to Marketplace (Public)'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    dependsOn: [Build, DeployDEV]
    jobs:
      - deployment:
        environment: Production
        strategy: 
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: vsix
                  patterns: "**/*-public.vsix"
                - task: TfxInstaller@4
                  displayName: 'Use Node CLI for Azure DevOps'
                  inputs:
                    version: '0.x'
                    checkLatest: true
                - task: PublishAzureDevOpsExtension@5
                  displayName: 'Publish Extension'
                  inputs:
                    connectTo: 'VsTeam'
                    connectedServiceName: 'Marketplace'
                    fileType: 'vsix'
                    vsixFile: '$(Pipeline.Workspace)/vsix/foxholenl-gitleaks-public.vsix'
                    updateTasksVersion: false
                    noWaitValidation:  true