title = "gitleaks config"

[[rules]]
id = "CSCAN0240-1" 
description = "VstsPersonalAccessToken 1" 
path = '''\.(?:cs|ps1|bat|config|xml|json)$'''
regex = '''(?i)(?:AccessToken|pat|token).*?[':="][a-z0-9]{52}(?:'|"|\s|[\r?\n]+)'''

[[rules]]
id = "CSCAN0240-2" 
description = "VstsPersonalAccessToken 2" 
path = '''\.(?:cs|ps1|bat|config|xml|json)$'''
regex = '''(?i)(?:AccessToken|pat|token).*?[':="][a-z0-9/+]{70}==(?:'|"|\s|[\r?\n]+)'''

[allowlist]
description = "global allow lists"
regexes = ['''219-09-9999''', '''078-05-1120''', '''(9[0-9]{2}|666)-\d{2}-\d{4}''']
files = ['''(.*?)(jpg|gif|doc|pdf|bin|svg|socket)$''']